.TH "Callbacks" 3 "Wed Jul 31 2024" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Callbacks \- Callbacks
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBRGFW_windowmovefunc\fP) (\fBRGFW_window\fP *win, \fBRGFW_rect\fP r)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_windowresizefunc\fP) (\fBRGFW_window\fP *win, \fBRGFW_rect\fP r)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_windowquitfunc\fP) (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_focusfunc\fP) (\fBRGFW_window\fP *win, \fBb8\fP inFocus)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_mouseNotifyfunc\fP) (\fBRGFW_window\fP *win, \fBRGFW_point\fP point, \fBb8\fP status)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_mouseposfunc\fP) (\fBRGFW_window\fP *win, \fBRGFW_point\fP point)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_dndInitfunc\fP) (\fBRGFW_window\fP *win, \fBRGFW_point\fP point)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_windowrefreshfunc\fP) (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_keyfunc\fP) (\fBRGFW_window\fP *win, \fBu32\fP keycode, char keyName[16], \fBu8\fP lockState, \fBb8\fP pressed)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_mousebuttonfunc\fP) (\fBRGFW_window\fP *win, \fBu8\fP button, double scroll, \fBb8\fP pressed)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_jsButtonfunc\fP) (\fBRGFW_window\fP *win, \fBu16\fP joystick, \fBu8\fP button, \fBb8\fP pressed)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_jsAxisfunc\fP) (\fBRGFW_window\fP *win, \fBu16\fP joystick, \fBRGFW_point\fP axis[2], \fBu8\fP axisesCount)"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_dndfunc\fP) (\fBRGFW_window\fP *win, char droppedFiles[\fBRGFW_MAX_DROPS\fP][\fBRGFW_MAX_PATH\fP], \fBu32\fP droppedFilesCount)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowmovefunc\fP \fBRGFW_setWindowMoveCallback\fP (\fBRGFW_windowmovefunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowresizefunc\fP \fBRGFW_setWindowResizeCallback\fP (\fBRGFW_windowresizefunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowquitfunc\fP \fBRGFW_setWindowQuitCallback\fP (\fBRGFW_windowquitfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_mouseposfunc\fP \fBRGFW_setMousePosCallback\fP (\fBRGFW_mouseposfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowrefreshfunc\fP \fBRGFW_setWindowRefreshCallback\fP (\fBRGFW_windowrefreshfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_focusfunc\fP \fBRGFW_setFocusCallback\fP (\fBRGFW_focusfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_mouseNotifyfunc\fP \fBRGFW_setMouseNotifyCallBack\fP (\fBRGFW_mouseNotifyfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_dndfunc\fP \fBRGFW_setDndCallback\fP (\fBRGFW_dndfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_dndInitfunc\fP \fBRGFW_setDndInitCallback\fP (\fBRGFW_dndInitfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_keyfunc\fP \fBRGFW_setKeyCallback\fP (\fBRGFW_keyfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_mousebuttonfunc\fP \fBRGFW_setMouseButtonCallback\fP (\fBRGFW_mousebuttonfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_jsButtonfunc\fP \fBRGFW_setjsButtonCallback\fP (\fBRGFW_jsButtonfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_jsAxisfunc\fP \fBRGFW_setjsAxisCallback\fP (\fBRGFW_jsAxisfunc\fP func)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event callbacks, these are completely optional, you can use the normal RGFW_checkEvent() method if you prefer that 
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* RGFW_dndfunc) (\fBRGFW_window\fP *win, char droppedFiles[\fBRGFW_MAX_DROPS\fP][\fBRGFW_MAX_PATH\fP], \fBu32\fP droppedFilesCount)"
RGFW_dnd, the window that had the drop, the drop data and the amount files dropped returns previous callback function (if it was set) 
.SS "typedef void(* RGFW_dndInitfunc) (\fBRGFW_window\fP *win, \fBRGFW_point\fP point)"
RGFW_dnd_init, the window, the point of the drop on the windows 
.SS "typedef void(* RGFW_focusfunc) (\fBRGFW_window\fP *win, \fBb8\fP inFocus)"
RGFW_focusIn / RGFW_focusOut, the window who's focus has changed and if its inFocus 
.SS "typedef void(* RGFW_jsAxisfunc) (\fBRGFW_window\fP *win, \fBu16\fP joystick, \fBRGFW_point\fP axis[2], \fBu8\fP axisesCount)"
RGFW_jsAxisMove, the window that got the event, the joystick in question, the axis values and the amount of axises 
.SS "typedef void(* RGFW_jsButtonfunc) (\fBRGFW_window\fP *win, \fBu16\fP joystick, \fBu8\fP button, \fBb8\fP pressed)"
RGFW_jsButtonPressed / RGFW_jsButtonReleased, the window that got the event, the button that was pressed, the scroll value, if it was a press (else it's a release) 
.SS "typedef void(* RGFW_keyfunc) (\fBRGFW_window\fP *win, \fBu32\fP keycode, char keyName[16], \fBu8\fP lockState, \fBb8\fP pressed)"
RGFW_keyPressed / RGFW_keyReleased, the window that got the event, the keycode, the string version, the state of mod keys, if it was a press (else it's a release) 
.SS "typedef void(* RGFW_mousebuttonfunc) (\fBRGFW_window\fP *win, \fBu8\fP button, double scroll, \fBb8\fP pressed)"
RGFW_mouseButtonPressed / RGFW_mouseButtonReleased, the window that got the event, the button that was pressed, the scroll value, if it was a press (else it's a release) 
.br
 
.SS "typedef void(* RGFW_mouseNotifyfunc) (\fBRGFW_window\fP *win, \fBRGFW_point\fP point, \fBb8\fP status)"
RGFW_mouseEnter / RGFW_mouseLeave, the window that changed, the point of the mouse (enter only) and if the mouse has entered 
.SS "typedef void(* RGFW_mouseposfunc) (\fBRGFW_window\fP *win, \fBRGFW_point\fP point)"
RGFW_mousePosChanged, the window that the move happened on and the new point of the mouse 
.br
 
.SS "typedef void(* RGFW_windowmovefunc) (\fBRGFW_window\fP *win, \fBRGFW_rect\fP r)"
RGFW_windowMoved, the window and its new rect value 
.br
 
.SS "typedef void(* RGFW_windowquitfunc) (\fBRGFW_window\fP *win)"
RGFW_quit, the window that was closed 
.SS "typedef void(* RGFW_windowrefreshfunc) (\fBRGFW_window\fP *win)"
RGFW_windowRefresh, the window that needs to be refreshed 
.SS "typedef void(* RGFW_windowresizefunc) (\fBRGFW_window\fP *win, \fBRGFW_rect\fP r)"
RGFW_windowResized, the window and its new rect value 
.br
 
.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP \fBRGFW_dndfunc\fP RGFW_setDndCallback (\fBRGFW_dndfunc\fP func)"
set callback for a drop event event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_dndInitfunc\fP RGFW_setDndInitCallback (\fBRGFW_dndInitfunc\fP func)"
set callback for a start of a drop event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_focusfunc\fP RGFW_setFocusCallback (\fBRGFW_focusfunc\fP func)"
set callback for a window focus change event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_jsAxisfunc\fP RGFW_setjsAxisCallback (\fBRGFW_jsAxisfunc\fP func)"
set callback for a joystick axis mov event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_jsButtonfunc\fP RGFW_setjsButtonCallback (\fBRGFW_jsButtonfunc\fP func)"
set callback for a controller button (press / release ) event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_keyfunc\fP RGFW_setKeyCallback (\fBRGFW_keyfunc\fP func)"
set callback for a key (press / release ) event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_mousebuttonfunc\fP RGFW_setMouseButtonCallback (\fBRGFW_mousebuttonfunc\fP func)"
set callback for a mouse button (press / release ) event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_mouseNotifyfunc\fP RGFW_setMouseNotifyCallBack (\fBRGFW_mouseNotifyfunc\fP func)"
set callback for a mouse notify event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_mouseposfunc\fP RGFW_setMousePosCallback (\fBRGFW_mouseposfunc\fP func)"
set callback for a mouse move event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_windowmovefunc\fP RGFW_setWindowMoveCallback (\fBRGFW_windowmovefunc\fP func)"
set callback for a window move event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_windowquitfunc\fP RGFW_setWindowQuitCallback (\fBRGFW_windowquitfunc\fP func)"
set callback for a window quit event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_windowrefreshfunc\fP RGFW_setWindowRefreshCallback (\fBRGFW_windowrefreshfunc\fP func)"
set callback for a window refresh event returns previous callback function (if it was set) 
.br
 
.SS "\fBRGFWDEF\fP \fBRGFW_windowresizefunc\fP RGFW_setWindowResizeCallback (\fBRGFW_windowresizefunc\fP func)"
set callback for a window resize event returns previous callback function (if it was set) 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
