.TH "Callbacks" 3 "Tue Nov 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Callbacks \- Callbacks
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowMovedfunc\fP \fBRGFW_setWindowMovedCallback\fP (\fBRGFW_windowMovedfunc\fP func)"
.br
.RI "Sets the callback function for window move events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowResizedfunc\fP \fBRGFW_setWindowResizedCallback\fP (\fBRGFW_windowResizedfunc\fP func)"
.br
.RI "Sets the callback function for window resize events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowQuitfunc\fP \fBRGFW_setWindowQuitCallback\fP (\fBRGFW_windowQuitfunc\fP func)"
.br
.RI "Sets the callback function for window quit events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_mousePosfunc\fP \fBRGFW_setMousePosCallback\fP (\fBRGFW_mousePosfunc\fP func)"
.br
.RI "Sets the callback function for mouse move events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowRefreshfunc\fP \fBRGFW_setWindowRefreshCallback\fP (\fBRGFW_windowRefreshfunc\fP func)"
.br
.RI "Sets the callback function for window refresh events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_focusfunc\fP \fBRGFW_setFocusCallback\fP (\fBRGFW_focusfunc\fP func)"
.br
.RI "Sets the callback function for focus change events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_mouseNotifyfunc\fP \fBRGFW_setMouseNotifyCallback\fP (\fBRGFW_mouseNotifyfunc\fP func)"
.br
.RI "Sets the callback function for mouse notification events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_dataDropfunc\fP \fBRGFW_setDataDropCallback\fP (\fBRGFW_dataDropfunc\fP func)"
.br
.RI "Sets the callback function for data drop events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_dataDragfunc\fP \fBRGFW_setDataDragCallback\fP (\fBRGFW_dataDragfunc\fP func)"
.br
.RI "Sets the callback function for the start of a data drag event\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_keyfunc\fP \fBRGFW_setKeyCallback\fP (\fBRGFW_keyfunc\fP func)"
.br
.RI "Sets the callback function for key press and release events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_mouseButtonfunc\fP \fBRGFW_setMouseButtonCallback\fP (\fBRGFW_mouseButtonfunc\fP func)"
.br
.RI "Sets the callback function for mouse button press and release events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_mouseScrollfunc\fP \fBRGFW_setMouseScrollCallback\fP (\fBRGFW_mouseScrollfunc\fP func)"
.br
.RI "Sets the callback function for mouse scroll events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowMaximizedfunc\fP \fBRGFW_setWindowMaximizedCallback\fP (\fBRGFW_windowMaximizedfunc\fP func)"
.br
.RI "Sets the callback function for window maximize events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowMinimizedfunc\fP \fBRGFW_setWindowMinimizedCallback\fP (\fBRGFW_windowMinimizedfunc\fP func)"
.br
.RI "Sets the callback function for window minimize events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_windowRestoredfunc\fP \fBRGFW_setWindowRestoredCallback\fP (\fBRGFW_windowRestoredfunc\fP func)"
.br
.RI "Sets the callback function for window restore events\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_scaleUpdatedfunc\fP \fBRGFW_setScaleUpdatedCallback\fP (\fBRGFW_scaleUpdatedfunc\fP func)"
.br
.RI "Sets the callback function for DPI (scale) update events\&. "
.in -1c
.SH "Detailed Description"
.PP 
event callbacks\&. These are completely optional, so you can use the normal RGFW_checkEvent() method if you prefer that 
.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP \fBRGFW_dataDragfunc\fP RGFW_setDataDragCallback (\fBRGFW_dataDragfunc\fP func)"

.PP
Sets the callback function for the start of a data drag event\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when data dragging begins\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_dataDropfunc\fP RGFW_setDataDropCallback (\fBRGFW_dataDropfunc\fP func)"

.PP
Sets the callback function for data drop events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when data is dropped into the window\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_focusfunc\fP RGFW_setFocusCallback (\fBRGFW_focusfunc\fP func)"

.PP
Sets the callback function for focus change events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window gains or loses focus\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_keyfunc\fP RGFW_setKeyCallback (\fBRGFW_keyfunc\fP func)"

.PP
Sets the callback function for key press and release events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when a key is pressed or released\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_mouseButtonfunc\fP RGFW_setMouseButtonCallback (\fBRGFW_mouseButtonfunc\fP func)"

.PP
Sets the callback function for mouse button press and release events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when a mouse button is pressed or released\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_mouseNotifyfunc\fP RGFW_setMouseNotifyCallback (\fBRGFW_mouseNotifyfunc\fP func)"

.PP
Sets the callback function for mouse notification events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when a mouse notification event occurs\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_mousePosfunc\fP RGFW_setMousePosCallback (\fBRGFW_mousePosfunc\fP func)"

.PP
Sets the callback function for mouse move events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the mouse moves within the window\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_mouseScrollfunc\fP RGFW_setMouseScrollCallback (\fBRGFW_mouseScrollfunc\fP func)"

.PP
Sets the callback function for mouse scroll events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the mouse wheel is scrolled\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_scaleUpdatedfunc\fP RGFW_setScaleUpdatedCallback (\fBRGFW_scaleUpdatedfunc\fP func)"

.PP
Sets the callback function for DPI (scale) update events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window’s DPI or scale changes\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_windowMaximizedfunc\fP RGFW_setWindowMaximizedCallback (\fBRGFW_windowMaximizedfunc\fP func)"

.PP
Sets the callback function for window maximize events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window is maximized\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_windowMinimizedfunc\fP RGFW_setWindowMinimizedCallback (\fBRGFW_windowMinimizedfunc\fP func)"

.PP
Sets the callback function for window minimize events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window is minimized\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_windowMovedfunc\fP RGFW_setWindowMovedCallback (\fBRGFW_windowMovedfunc\fP func)"

.PP
Sets the callback function for window move events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window is moved\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_windowQuitfunc\fP RGFW_setWindowQuitCallback (\fBRGFW_windowQuitfunc\fP func)"

.PP
Sets the callback function for window quit events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window receives a quit signal\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_windowRefreshfunc\fP RGFW_setWindowRefreshCallback (\fBRGFW_windowRefreshfunc\fP func)"

.PP
Sets the callback function for window refresh events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window needs to be refreshed\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_windowResizedfunc\fP RGFW_setWindowResizedCallback (\fBRGFW_windowResizedfunc\fP func)"

.PP
Sets the callback function for window resize events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window is resized\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_windowRestoredfunc\fP RGFW_setWindowRestoredCallback (\fBRGFW_windowRestoredfunc\fP func)"

.PP
Sets the callback function for window restore events\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIfunc\fP The function to be called when the window is restored from a minimized or maximized state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The previously set callback function, if any\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
