.TH "Clipboard" 3 "Thu Jun 25 2026" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clipboard \- Clipboard
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP const \fBRGFW_dataTransfer\fP * \fBRGFW_readClipboard\fP (void)"
.br
.RI "Reads clipboard data\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_readClipboardPtr\fP (\fBu8\fP *buffer, size_t capacity, \fBRGFW_dataTransfer\fP *data)"
.br
.RI "Reads clipboard data into your object pointer using your provided buffer, or returns the required length if the buffer is NULL or bufferCapacity is 0\&. "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_writeClipboard\fP (const \fBRGFW_dataTransfer\fP *data)"
.br
.RI "Writes data to the clipboard\&. "
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP const \fBRGFW_dataTransfer\fP * RGFW_readClipboard (void)"

.PP
Reads clipboard data\&. ! 
.PP
\fBReturns\fP
.RS 4
A pointer to the clipboard data object or NULL on failure\&. 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_readClipboardPtr (\fBu8\fP * buffer, size_t capacity, \fBRGFW_dataTransfer\fP * data)"

.PP
Reads clipboard data into your object pointer using your provided buffer, or returns the required length if the buffer is NULL or bufferCapacity is 0\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP the buffer used to fill the output dataTransfer object's data 
.br
\fIcapacity\fP the capacity/length of the buffer in bytes 
.br
\fIdata\fP [OUTPUT] A pointer to the dataTransfer object that will receive the clipboard data\&. (cannot be NULL) 
.RE
.PP
\fBReturns\fP
.RS 4
returns RGFW_TRUE on success and RGFW_FALSE on failure 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_writeClipboard (const \fBRGFW_dataTransfer\fP * data)"

.PP
Writes data to the clipboard\&. ! 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP The data to be written to the clipboard, including the length and type\&. 
.br
\fIreturns\fP RGFW_TRUE on success and RGFW_FALSE on failure 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
