.TH "Clipboard" 3 "Sun Aug 10 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clipboard \- Clipboard
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef ptrdiff_t \fBRGFW_ssize_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP const char * \fBRGFW_readClipboard\fP (size_t *size)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_ssize_t\fP \fBRGFW_readClipboardPtr\fP (char *str, size_t strCapacity)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_writeClipboard\fP (const char *text, \fBu32\fP textLen)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef ptrdiff_t \fBRGFW_ssize_t\fP"

.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP const char * RGFW_readClipboard (size_t * size)"
read clipboard data 
.SS "\fBRGFWDEF\fP \fBRGFW_ssize_t\fP RGFW_readClipboardPtr (char * str, size_t strCapacity)"
read clipboard data or send a NULL str to just get the length of the clipboard data 
.SS "\fBRGFWDEF\fP void RGFW_writeClipboard (const char * text, \fBu32\fP textLen)"
write text to the clipboard 
.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
