.TH "error" 3 "Sat Jul 19 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error \- handling
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRGFW_debugContext\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRGFW_DEBUG_CTX\fP(win,  err)   (\fBRGFW_debugContext\fP){win, NULL, err}"
.br
.ti -1c
.RI "#define \fBRGFW_DEBUG_CTX_MON\fP(monitor)   (\fBRGFW_debugContext\fP){_RGFW\->root, &monitor, 0}"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBRGFW_debugContext\fP \fBRGFW_debugContext\fP"
.br
.ti -1c
.RI "typedef void(* \fBRGFW_debugfunc\fP) (RGFW_debugType type, RGFW_errorCode err, \fBRGFW_debugContext\fP ctx, const char *msg)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fBRGFW_ENUM\fP (\fBu8\fP, RGFW_debugType)"
.br
.ti -1c
.RI "typedef \fBRGFW_ENUM\fP (\fBu8\fP, RGFW_errorCode)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_debugfunc\fP \fBRGFW_setDebugCallback\fP (\fBRGFW_debugfunc\fP func)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_sendDebugInfo\fP (RGFW_debugType type, RGFW_errorCode err, \fBRGFW_debugContext\fP ctx, const char *msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define RGFW_DEBUG_CTX(win, err)   (\fBRGFW_debugContext\fP){win, NULL, err}"

.SS "#define RGFW_DEBUG_CTX_MON(monitor)   (\fBRGFW_debugContext\fP){_RGFW\->root, &monitor, 0}"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBRGFW_debugContext\fP \fBRGFW_debugContext\fP"

.SS "typedef void(* RGFW_debugfunc) (RGFW_debugType type, RGFW_errorCode err, \fBRGFW_debugContext\fP ctx, const char *msg)"

.SH "Function Documentation"
.PP 
.SS "typedef RGFW_ENUM (\fBu8\fP, RGFW_debugType)"

.SS "typedef RGFW_ENUM (\fBu8\fP, RGFW_errorCode)"
< no error
.PP
< error with the OpenGL context
.SS "\fBRGFWDEF\fP void RGFW_sendDebugInfo (RGFW_debugType type, RGFW_errorCode err, \fBRGFW_debugContext\fP ctx, const char * msg)"

.SS "\fBRGFWDEF\fP \fBRGFW_debugfunc\fP RGFW_setDebugCallback (\fBRGFW_debugfunc\fP func)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
