.TH "gamepad" 3 "Fri Jul 11 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamepad \- Gamepad
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fBRGFW_ENUM\fP (\fBu8\fP, RGFW_gamepadType)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBu32\fP \fBRGFW_isPressedGamepad\fP (\fBRGFW_window\fP *win, \fBu8\fP controller, RGFW_gamepadCodes button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBu32\fP \fBRGFW_isReleasedGamepad\fP (\fBRGFW_window\fP *win, \fBu8\fP controller, RGFW_gamepadCodes button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBu32\fP \fBRGFW_isHeldGamepad\fP (\fBRGFW_window\fP *win, \fBu8\fP controller, RGFW_gamepadCodes button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBu32\fP \fBRGFW_wasPressedGamepad\fP (\fBRGFW_window\fP *win, \fBu8\fP controller, RGFW_gamepadCodes button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_point\fP \fBRGFW_getGamepadAxis\fP (\fBRGFW_window\fP *win, \fBu16\fP controller, \fBu16\fP whichAxis)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP const char * \fBRGFW_getGamepadName\fP (\fBRGFW_window\fP *win, \fBu16\fP controller)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP size_t \fBRGFW_getGamepadCount\fP (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP RGFW_gamepadType \fBRGFW_getGamepadType\fP (\fBRGFW_window\fP *win, \fBu16\fP controller)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Function Documentation"
.PP 
.SS "typedef RGFW_ENUM (\fBu8\fP, RGFW_gamepadType)"

.SS "\fBRGFWDEF\fP \fBRGFW_point\fP RGFW_getGamepadAxis (\fBRGFW_window\fP * win, \fBu16\fP controller, \fBu16\fP whichAxis)"

.SS "\fBRGFWDEF\fP size_t RGFW_getGamepadCount (\fBRGFW_window\fP * win)"

.SS "\fBRGFWDEF\fP const char * RGFW_getGamepadName (\fBRGFW_window\fP * win, \fBu16\fP controller)"

.SS "\fBRGFWDEF\fP RGFW_gamepadType RGFW_getGamepadType (\fBRGFW_window\fP * win, \fBu16\fP controller)"

.SS "\fBRGFWDEF\fP \fBu32\fP RGFW_isHeldGamepad (\fBRGFW_window\fP * win, \fBu8\fP controller, RGFW_gamepadCodes button)"

.SS "\fBRGFWDEF\fP \fBu32\fP RGFW_isPressedGamepad (\fBRGFW_window\fP * win, \fBu8\fP controller, RGFW_gamepadCodes button)"
gamepad count starts at 0 
.SS "\fBRGFWDEF\fP \fBu32\fP RGFW_isReleasedGamepad (\fBRGFW_window\fP * win, \fBu8\fP controller, RGFW_gamepadCodes button)"

.SS "\fBRGFWDEF\fP \fBu32\fP RGFW_wasPressedGamepad (\fBRGFW_window\fP * win, \fBu8\fP controller, RGFW_gamepadCodes button)"

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
