.TH "graphics_API" 3 "Wed Jul 16 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics_API \- Graphics_API
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBRGFW_proc\fP) (void)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_window_makeCurrent\fP (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_window\fP * \fBRGFW_getCurrent\fP (void)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_window_swapBuffers\fP (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_window_swapInterval\fP (\fBRGFW_window\fP *win, \fBi32\fP swapInterval)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_window_swapBuffers_software\fP (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_window_initOpenGL\fP (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_window_freeOpenGL\fP (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "typedef \fBRGFW_ENUM\fP (\fBi32\fP, RGFW_glHints)"
.br
.ti -1c
.RI "typedef \fBRGFW_ENUM\fP (\fBi32\fP, RGFW_glValue)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_setGLHint\fP (RGFW_glHints hint, \fBi32\fP value)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBi32\fP \fBRGFW_getGLHint\fP (RGFW_glHints hint)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_window_makeCurrent_OpenGL\fP (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_window_swapBuffers_OpenGL\fP (\fBRGFW_window\fP *win)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void * \fBRGFW_getCurrent_OpenGL\fP (void)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_proc\fP \fBRGFW_getProcAddress\fP (const char *procname)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_extensionSupported\fP (const char *extension, size_t len)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_extensionSupportedPlatform\fP (const char *extension, size_t len)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef void(* RGFW_proc) (void)"

.SH "Function Documentation"
.PP 
.SS "typedef RGFW_ENUM (\fBi32\fP, RGFW_glHints)"
OpenGL init hints < set stencil buffer bit size (0 by default)
.PP
< set number of sample buffers (0 by default)
.PP
< hint the context to use stereoscopic frame buffers for 3D (false by default)
.PP
< number of aux buffers (0 by default)
.PP
< request double buffering (true by default)
.PP
< set color bit sizes (all 8 by default)
.PP
< set depth buffer bit size (24 by default)
.PP
< set accumulated RGBA bit sizes (all 0 by default)
.PP
< request sRGA format (false by default)
.PP
< request a 'robust' (as in memory-safe) context (false by default)\&. For more information check the overview section: https://registry.khronos.org/OpenGL/extensions/EXT/EXT_robustness.txt
.PP
< request OpenGL debugging (false by default)\&.
.PP
< request no OpenGL errors (false by default)\&. This causes OpenGL errors to be undefined behavior\&. For more information check the overview section: https://registry.khronos.org/OpenGL/extensions/KHR/KHR_no_error.txt
.PP
< hint how the OpenGL driver should behave when changing contexts (RGFW_glReleaseNone by default)\&. For more information check the overview section: https://registry.khronos.org/OpenGL/extensions/KHR/KHR_context_flush_control.txt
.PP
< set OpenGL API profile (RGFW_glCore by default)
.PP
< set the OpenGL API profile version (by default RGFW_glMajor is 1, RGFW_glMinor is 0)
.SS "typedef RGFW_ENUM (\fBi32\fP, RGFW_glValue)"
< RGFW_glProfile options
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_extensionSupported (const char * extension, size_t len)"
check if whether the specified API extension is supported by the current OpenGL or OpenGL ES context 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_extensionSupportedPlatform (const char * extension, size_t len)"
check if whether the specified platform-specific API extension is supported by the current OpenGL or OpenGL ES context 
.SS "\fBRGFWDEF\fP \fBRGFW_window\fP * RGFW_getCurrent (void)"
get current RGFW window graphics context 
.SS "\fBRGFWDEF\fP void * RGFW_getCurrent_OpenGL (void)"
get the current context (OpenGL backend (GLX) (WGL) (EGL) (cocoa) (webgl)) 
.SS "\fBRGFWDEF\fP \fBi32\fP RGFW_getGLHint (RGFW_glHints hint)"

.SS "\fBRGFWDEF\fP \fBRGFW_proc\fP RGFW_getProcAddress (const char * procname)"
get native OpenGL proc address 
.SS "\fBRGFWDEF\fP void RGFW_setGLHint (RGFW_glHints hint, \fBi32\fP value)"

.SS "\fBRGFWDEF\fP void RGFW_window_freeOpenGL (\fBRGFW_window\fP * win)"

.SS "\fBRGFWDEF\fP void RGFW_window_initOpenGL (\fBRGFW_window\fP * win)"
native API functions
.PP
< create an OpenGL context for the RGFW window, run by createWindow by default (unless the RGFW_windowNoInitAPI is included) called by \fCRGFW_window_close\fP by default (unless the RGFW_windowNoInitAPI is set) 
.SS "\fBRGFWDEF\fP void RGFW_window_makeCurrent (\fBRGFW_window\fP * win)"
< make the window the current OpenGL drawing context
.PP
NOTE: if you want to switch the graphics context's thread, you have to run RGFW_window_makeCurrent(NULL); on the old thread then RGFW_window_makeCurrent(valid_window) on the new thread 
.SS "\fBRGFWDEF\fP void RGFW_window_makeCurrent_OpenGL (\fBRGFW_window\fP * win)"
to be called by RGFW_window_makeCurrent 
.SS "\fBRGFWDEF\fP void RGFW_window_swapBuffers (\fBRGFW_window\fP * win)"
swap the rendering buffer 
.SS "\fBRGFWDEF\fP void RGFW_window_swapBuffers_OpenGL (\fBRGFW_window\fP * win)"
swap OpenGL buffer (only) called by RGFW_window_swapInterval 
.br
 
.SS "\fBRGFWDEF\fP void RGFW_window_swapBuffers_software (\fBRGFW_window\fP * win)"

.SS "\fBRGFWDEF\fP void RGFW_window_swapInterval (\fBRGFW_window\fP * win, \fBi32\fP swapInterval)"
render the software rendering buffer (this is called by RGFW_window_swapInterval) 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
