.TH "Input" 3 "Fri Oct 17 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input \- Input
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isKeyPressed\fP (RGFW_key key)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isKeyDown\fP (RGFW_key key)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isKeyReleased\fP (RGFW_key key)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMousePressed\fP (RGFW_mouseButton button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMouseDown\fP (RGFW_mouseButton button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMouseReleased\fP (RGFW_mouseButton button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_getMouseScroll\fP (float *x, float *y)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_getMouseVector\fP (float *x, float *y)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP void RGFW_getMouseScroll (float * x, float * y)"
get the current scroll value (of the frame) 
.SS "\fBRGFWDEF\fP void RGFW_getMouseVector (float * x, float * y)"
get the current vector value (of the frame) 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isKeyDown (RGFW_key key)"
if key is held (key code) 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isKeyPressed (RGFW_key key)"
if key is pressed during the current frame (key code) 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isKeyReleased (RGFW_key key)"
if key is released (key code) 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMouseDown (RGFW_mouseButton button)"
if a mouse button is down 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP mouse button code 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMousePressed (RGFW_mouseButton button)"
if a mouse button is pressed during the current frame 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP mouse button code 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMouseReleased (RGFW_mouseButton button)"
if a mouse button was released 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP mouse button code 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
