.TH "Input" 3 "Tue Jul 22 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input \- Input
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isPressed\fP (\fBRGFW_window\fP *win, \fBRGFW_key\fP key)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_wasPressed\fP (\fBRGFW_window\fP *win, \fBRGFW_key\fP key)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isHeld\fP (\fBRGFW_window\fP *win, \fBRGFW_key\fP key)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isReleased\fP (\fBRGFW_window\fP *win, \fBRGFW_key\fP key)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isClicked\fP (\fBRGFW_window\fP *win, \fBRGFW_key\fP key)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMousePressed\fP (\fBRGFW_window\fP *win, RGFW_mouseButton button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMouseHeld\fP (\fBRGFW_window\fP *win, RGFW_mouseButton button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMouseReleased\fP (\fBRGFW_window\fP *win, RGFW_mouseButton button)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_wasMousePressed\fP (\fBRGFW_window\fP *win, RGFW_mouseButton button)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isClicked (\fBRGFW_window\fP * win, \fBRGFW_key\fP key)"

.PP
\fBParameters\fP
.RS 4
\fIkey\fP key code 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isHeld (\fBRGFW_window\fP * win, \fBRGFW_key\fP key)"
if key is held (key code) 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMouseHeld (\fBRGFW_window\fP * win, RGFW_mouseButton button)"
if a mouse button is held 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP mouse button code 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMousePressed (\fBRGFW_window\fP * win, RGFW_mouseButton button)"
if a mouse button is pressed 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP mouse button code 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMouseReleased (\fBRGFW_window\fP * win, RGFW_mouseButton button)"
if a mouse button was released 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP mouse button code 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isPressed (\fBRGFW_window\fP * win, \fBRGFW_key\fP key)"
if window == NULL, it checks if the key is pressed globally\&. Otherwise, it checks only if the key is pressed while the window in focus\&. if key is pressed (key code) 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isReleased (\fBRGFW_window\fP * win, \fBRGFW_key\fP key)"
if key is released (key code) 
.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_wasMousePressed (\fBRGFW_window\fP * win, RGFW_mouseButton button)"
if a mouse button was pressed (checks previous state only) 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP mouse button code 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_wasPressed (\fBRGFW_window\fP * win, \fBRGFW_key\fP key)"
if key was pressed (checks previous state only) (key code) 
.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
