.TH "Input" 3 "Tue Nov 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input \- Input
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isKeyPressed\fP (RGFW_key key)"
.br
.RI "returns true if the key is pressed during the current frame "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isKeyReleased\fP (RGFW_key key)"
.br
.RI "returns true if the key was released during the current frame "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isKeyDown\fP (RGFW_key key)"
.br
.RI "returns true if the key is down "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMousePressed\fP (RGFW_mouseButton button)"
.br
.RI "returns true if the mouse button is pressed during the current frame "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMouseReleased\fP (RGFW_mouseButton button)"
.br
.RI "returns true if the mouse button is released during the current frame "
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_bool\fP \fBRGFW_isMouseDown\fP (RGFW_mouseButton button)"
.br
.RI "returns true if the mouse button is down "
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_getMouseScroll\fP (float *x, float *y)"
.br
.RI "outputs the current x, y position of the mouse "
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_getMouseVector\fP (float *x, float *y)"
.br
.RI "outputs the current x, y movement vector of the mouse "
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP void RGFW_getMouseScroll (float * x, float * y)"

.PP
outputs the current x, y position of the mouse ! 
.PP
\fBParameters\fP
.RS 4
\fIX\fP [OUTPUT] a pointer for the output X value 
.br
\fIY\fP [OUTPUT] a pointer for the output Y value 
.RE
.PP

.SS "\fBRGFWDEF\fP void RGFW_getMouseVector (float * x, float * y)"

.PP
outputs the current x, y movement vector of the mouse ! 
.PP
\fBParameters\fP
.RS 4
\fIX\fP [OUTPUT] a pointer for the output X vector value 
.br
\fIY\fP [OUTPUT] a pointer for the output Y vector value 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isKeyDown (RGFW_key key)"

.PP
returns true if the key is down ! 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP the key code of the key you want to check 
.RE
.PP
\fBReturns\fP
.RS 4
The boolean value if the key is down or not 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isKeyPressed (RGFW_key key)"

.PP
returns true if the key is pressed during the current frame ! 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP the key code of the key you want to check 
.RE
.PP
\fBReturns\fP
.RS 4
The boolean value if the key is pressed or not 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isKeyReleased (RGFW_key key)"

.PP
returns true if the key was released during the current frame ! 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP the key code of the key you want to check 
.RE
.PP
\fBReturns\fP
.RS 4
The boolean value if the key is released or not 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMouseDown (RGFW_mouseButton button)"

.PP
returns true if the mouse button is down ! 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP the mouse button code of the button you want to check 
.RE
.PP
\fBReturns\fP
.RS 4
The boolean value if the button is down or not 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMousePressed (RGFW_mouseButton button)"

.PP
returns true if the mouse button is pressed during the current frame ! 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP the mouse button code of the button you want to check 
.RE
.PP
\fBReturns\fP
.RS 4
The boolean value if the button is pressed or not 
.RE
.PP

.SS "\fBRGFWDEF\fP \fBRGFW_bool\fP RGFW_isMouseReleased (RGFW_mouseButton button)"

.PP
returns true if the mouse button is released during the current frame ! 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP the mouse button code of the button you want to check 
.RE
.PP
\fBReturns\fP
.RS 4
The boolean value if the button is released or not 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
