.TH "md_README" 3 "Wed Jul 16 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- Riley's Graphics library FrameWork 
.PP

.SH "Build statuses"
.PP
  
.PP
\fC\fP.PP
A cross-platform lightweight single-header very simple-to-use window abstraction library for creating graphics Libraries or simple graphical programs\&. Written in pure C99\&.
.SH "About"
.PP
RGFW is a free multi-platform single-header very simple-to-use window abstraction framework for creating graphics Libraries or simple graphical programs\&. It is meant to be used as a very small and flexible alternative library to GLFW\&.
.PP
The window backend supports XLib (UNIX), Cocoas (MacOS), wasm (emscripten) and WinAPI (tested on windows \fIXP\fP, 10 and 11, and reactOS)\\ Windows 95 & 98 have also been tested with RGFW, although results are iffy 
.br
.PP
Wayland: to compile wayland add (RGFW_WAYLAND=1)\&. Wayland support is very experimental and broken\&.
.PP
The graphics backend supports OpenGL (EGL, software, OSMesa, GLES), Vulkan, DirectX, \fCMetal\fP and software rendering buffers\&.
.PP
RGFW was designed as a backend for RSGL, but it can be used standalone or for other libraries, such as Raylib which uses it as an optional alternative backend\&.
.PP
RGFW is multi-paradigm,\\ By default RGFW uses a flexible event system, similar to that of SDL, however you can use callbacks if you prefer that method\&.
.PP
This library
.PP
1) is single header and portable (written in C99 in mind) 2) is very small compared to other libraries 3) only depends on system API libraries, Winapi, X11, Cocoa 4) lets you create a window with a graphics context (OpenGL, Vulkan or DirectX) and manage the window and its events only with a few function calls 5) is customizable, you enable or disable features
.PP
This library does not
.PP
1) Handle any rendering for you (other than creating your graphics context) 2) do anything above the bare minimum in terms of functionality
.SH "Getting started"
.PP
.SS "a very simple example"
.PP
.nf
#define RGFW_IMPLEMENTATION
#include "RGFW\&.h"

#include <stdio\&.h>

void keyfunc(RGFW_window* win, RGFW_key key, u8 keyChar, RGFW_keymod keyMod, RGFW_bool pressed) {
    if (key == RGFW_escape && pressed) {
        RGFW_window_setShouldClose(win, 1);
    }
}

int main() {
    RGFW_window* win = RGFW_createWindow("a window", RGFW_RECT(0, 0, 800, 600), RGFW_windowCenter | RGFW_windowNoResize);

    RGFW_setKeyCallback(keyfunc); // you can use callbacks like this if you want

    while (RGFW_window_shouldClose(win) == RGFW_FALSE) {
        while (RGFW_window_checkEvent(win)) {  // or RGFW_window_checkEvents(); if you only want callbacks
            // you can either check the current event yourself
            if (win->event\&.type == RGFW_quit) break;
            
            if (win->event\&.type == RGFW_mouseButtonPressed && win->event\&.button == RGFW_mouseLeft) {
                printf("You clicked at x: %d, y: %d\n", win->event\&.point\&.x, win->event\&.point\&.y);
            }

            // or use the existing functions
            if (RGFW_isMousePressed(win, RGFW_mouseRight)) {
                printf("The right mouse button was clicked at x: %d, y: %d\n", win->event\&.point\&.x, win->event\&.point\&.y);
            }
        }
        
        glClearColor(0\&.1f, 0\&.1f, 0\&.1f, 1\&.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        // You can use modern OpenGL techniques, but this method is more straightforward for drawing just one triangle\&.
        glBegin(GL_TRIANGLES);
        glColor3f(1\&.0f, 0\&.0f, 0\&.0f); glVertex2f(-0\&.6f, -0\&.75f);
        glColor3f(0\&.0f, 1\&.0f, 0\&.0f); glVertex2f(0\&.6f, -0\&.75f);
        glColor3f(0\&.0f, 0\&.0f, 1\&.0f); glVertex2f(0\&.0f, 0\&.75f);
        glEnd();

        RGFW_window_swapBuffers(win);
    }

    RGFW_window_close(win);
    return 0;
}
.fi
.PP
.PP
.PP
.nf
linux : gcc main\&.c -lX11 -lGL -lXrandr
windows : gcc main\&.c -lopengl32 -lgdi32
macos : gcc main\&.c -framework CoreVideo -framework Cocoa -framework OpenGL -framework IOKit
.fi
.PP
.SS "Dynamic Linking with XDL\&.h"
XDL can be used to dynamically link X11 functions to RGFW using \fCdl\fP\&. It allows X11 functions to loaded at runtime\&.
.PP
To enable RGFW's use of XDL, add this line to your code:
.PP
.PP
.nf
#define RGFW_USE_XDL
.fi
.PP
.SS "Linking OpenGL is not required"
This only applies to Windows, macOS and X11 (with \fC\fBXDL\&.h\fP\fP):
.PP
By default, OpenGL does not need to be explicitly linked unless you are directly using OpenGL functions in your code\&. If you rely on a OpenGL loader library, you don't need to explicitly link OpenGL at all!
.PP
The examples/gl33/gl33 example demonstrates using OpenGL without explicitly linking it\&.
.SS "other examples"
.PP
You can find more examples [here](examples) or \fCrun it in your browser\fP with emscripten
.SH "Officially tested Platforms"
.PP
.IP "\(bu" 2
Windows (ReactOS, XP, Windows 10, 11)
.IP "\(bu" 2
Linux
.IP "\(bu" 2
MacOS (10\&.13, 10\&.14, 10\&.15) (x86_64)
.IP "\(bu" 2
HTML5 (wasm / Emscripten)
.IP "\(bu" 2
Raspberry PI OS
.PP
.SH "Supported GUI libraries"
.PP
A list of GUI libraries that can be used with RGFW can be found on the RGFW wiki \fChere\fP
.SH "Documentation"
.PP
There is a lot of in-header-documentation, but more documentation can be found at https://colleagueriley.github.io/RGFW/docs/index.html If you wish to build the documentation yourself, there is also a Doxygen file attached\&.
.SH "Bindings"
.PP
A list of bindings can be found on the RGFW wiki \fChere\fP
.SH "projects"
.PP
A list of projects that use RGFW can be found on the RGFW wiki \fChere\fP
.SH "Contacts"
.PP
.IP "\(bu" 2
email : ColleagueRiley@gmail.com
.IP "\(bu" 2
discord : ColleagueRiley
.IP "\(bu" 2
discord server : https://discord.gg/pXVNgVVbvh
.IP "\(bu" 2
matrix space: https://matrix.to/#/#rsgl-is-sili:matrix.org
.IP "\(bu" 2
BlueSky https://bsky.app/profile/colleagueriley.bsky.social
.IP "\(bu" 2
Twitter/X : https://x.com/ColleagueRiley
.PP
.SH "Supporting RGFW"
.PP
There is a RGFW wiki page about things you can do if you want to support the development of RGFW \fChere\fP\&.
.SH "RGFW vs GLFW"
.PP
A comparison of RGFW and GLFW can be found at \fCon the wiki\fP
.SH "License"
.PP
RGFW uses the Zlib/libPNG license, this means you can use RGFW freely as long as you do not claim you wrote this software, mark altered versions as such and keep the license included with the header\&.
.PP
.PP
.nf
Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:
  
1\&. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software\&. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required\&. 
2\&. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software\&.
3\&. This notice may not be removed or altered from any source distribution\&.
.fi
.PP
 
