.TH "RGFW_event" 3 "Sat Jul 19 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RGFW_eventType \fBtype\fP"
.br
.ti -1c
.RI "\fBRGFW_point\fP \fBpoint\fP"
.br
.ti -1c
.RI "\fBRGFW_point\fP \fBvector\fP"
.br
.ti -1c
.RI "float \fBscaleX\fP"
.br
.ti -1c
.RI "float \fBscaleY\fP"
.br
.ti -1c
.RI "\fBRGFW_key\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBkeyChar\fP"
.br
.ti -1c
.RI "\fBRGFW_bool\fP \fBrepeat\fP"
.br
.ti -1c
.RI "RGFW_keymod \fBkeyMod\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBbutton\fP"
.br
.ti -1c
.RI "double \fBscroll\fP"
.br
.ti -1c
.RI "char ** \fBdroppedFiles\fP"
.br
.ti -1c
.RI "size_t \fBdroppedFilesCount\fP"
.br
.ti -1c
.RI "void * \fB_win\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event structure for checking/getting events 
.SH "Member Data Documentation"
.PP 
.SS "void* RGFW_event::_win"
the window this event applies too (for event queue events) 
.SS "\fBu8\fP RGFW_event::button"

.SS "char** RGFW_event::droppedFiles"
drag and drop data dropped files 
.SS "size_t RGFW_event::droppedFilesCount"
house many files were dropped 
.SS "\fBRGFW_key\fP RGFW_event::key"
the physical key of the event, refers to where key is physically !!Keycodes defined at the bottom of the RGFW_HEADER part of this file!! 
.SS "\fBu8\fP RGFW_event::keyChar"
mapped key char of the event 
.SS "RGFW_keymod RGFW_event::keyMod"

.SS "\fBRGFW_point\fP RGFW_event::point"
mouse x, y of event (or drop point) 
.SS "\fBRGFW_bool\fP RGFW_event::repeat"
key press event repeated (the key is being held) 
.SS "float RGFW_event::scaleX"

.SS "float RGFW_event::scaleY"
DPI scaling 
.SS "double RGFW_event::scroll"
the raw mouse scroll value 
.SS "RGFW_eventType RGFW_event::type"
which event has been sent? 
.SS "\fBRGFW_point\fP RGFW_event::vector"
raw mouse movement 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
