.TH "RGFW_debugContext" 3 "Fri Jul 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_debugContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRGFW_window\fP * \fBwin\fP"
.br
.ti -1c
.RI "\fBRGFW_monitor\fP * \fBmonitor\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBsrcError\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_monitor\fP* RGFW_debugContext::monitor"

.SS "\fBu32\fP RGFW_debugContext::srcError"

.SS "\fBRGFW_window\fP* RGFW_debugContext::win"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
