.TH "RGFW_allocator" 3 "Sun Jan 12 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_allocator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "\fBRGFW_allocatorMallocfunc\fP \fBalloc\fP"
.br
.ti -1c
.RI "\fBRGFW_allocatorFreefunc\fP \fBfree\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_allocatorMallocfunc\fP RGFW_allocator::alloc"

.SS "\fBRGFW_allocatorFreefunc\fP RGFW_allocator::free"

.SS "void* RGFW_allocator::userdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
