.TH "RGFW_surface" 3 "Sun Jul 27 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_surface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRGFW_image\fP \fBimage\fP"
.br
.ti -1c
.RI "\fBRGFW_nativeImage\fP \fBnative\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
source data for the window (used by the APIs) 
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_image\fP RGFW_surface::image"

.SS "\fBRGFW_nativeImage\fP RGFW_surface::native"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
