.TH "RGFW_monitorMode" 3 "Wed Jul 23 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_monitorMode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRGFW_area\fP \fBarea\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBrefreshRate\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBred\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBblue\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBgreen\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_area\fP RGFW_monitorMode::area"
monitor workarea size 
.SS "\fBu8\fP RGFW_monitorMode::blue"

.SS "\fBu8\fP RGFW_monitorMode::green"

.SS "\fBu8\fP RGFW_monitorMode::red"

.SS "\fBu32\fP RGFW_monitorMode::refreshRate"
monitor refresh rate 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
