.TH "RGFW_window_fat" 3 "Sun Jul 20 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_window_fat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRGFW_window\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBRGFW_window_src\fP \fBsrc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
source data for the window (used by the APIs) 
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_window\fP RGFW_window_fat::base"
src window data 
.SS "\fBRGFW_window_src\fP RGFW_window_fat::src"
src window data 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
