.TH "RGFW_dataDragEvent" 3 "Tue Nov 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_dataDragEvent \- event data for any data drag event  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RGFW_eventType \fBtype\fP"
.br
.ti -1c
.RI "\fBRGFW_window\fP * \fBwin\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBx\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
event data for any data drag event 
.SH "Member Data Documentation"
.PP 
.SS "RGFW_eventType RGFW_dataDragEvent::type"
which event has been sent? 
.SS "\fBRGFW_window\fP* RGFW_dataDragEvent::win"
the window this event applies too (for event queue events) 
.SS "\fBi32\fP RGFW_dataDragEvent::x"

.SS "\fBi32\fP RGFW_dataDragEvent::y"
mouse x, y of event (or drop point) 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
