.TH "RGFW_event" 3 "Tue Nov 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_event \- union for all of the event stucture types  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RGFW_eventType \fBtype\fP"
.br
.ti -1c
.RI "\fBRGFW_commonEvent\fP \fBcommon\fP"
.br
.ti -1c
.RI "\fBRGFW_mouseButtonEvent\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBRGFW_mouseScrollEvent\fP \fBscroll\fP"
.br
.ti -1c
.RI "\fBRGFW_mousePosEvent\fP \fBmouse\fP"
.br
.ti -1c
.RI "\fBRGFW_keyEvent\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBRGFW_dataDropEvent\fP \fBdrop\fP"
.br
.ti -1c
.RI "\fBRGFW_dataDragEvent\fP \fBdrag\fP"
.br
.ti -1c
.RI "\fBRGFW_scaleUpdatedEvent\fP \fBscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
union for all of the event stucture types 
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_mouseButtonEvent\fP RGFW_event::button"
data for a button press/release 
.SS "\fBRGFW_commonEvent\fP RGFW_event::common"
common event data (e\&.g\&.) type and win 
.SS "\fBRGFW_dataDragEvent\fP RGFW_event::drag"

.SS "\fBRGFW_dataDropEvent\fP RGFW_event::drop"
dropping a file events 
.SS "\fBRGFW_keyEvent\fP RGFW_event::key"
data for key press/release/hold events 
.SS "\fBRGFW_mousePosEvent\fP RGFW_event::mouse"
data for mouse motion events 
.SS "\fBRGFW_scaleUpdatedEvent\fP RGFW_event::scale"

.SS "\fBRGFW_mouseScrollEvent\fP RGFW_event::scroll"
data for a mouse scroll 
.SS "RGFW_eventType RGFW_event::type"
which event has been sent? 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
