.TH "RGFW_gammaRamp" 3 "Tue Feb 24 2026" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_gammaRamp \- gamma struct for monitors  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu16\fP * \fBred\fP"
.br
.ti -1c
.RI "\fBu16\fP * \fBgreen\fP"
.br
.ti -1c
.RI "\fBu16\fP * \fBblue\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
gamma struct for monitors 
.SH "Member Data Documentation"
.PP 
.SS "\fBu16\fP* RGFW_gammaRamp::blue"
array for the blue channel 
.SS "size_t RGFW_gammaRamp::count"

.SS "\fBu16\fP* RGFW_gammaRamp::green"
array for the green channel 
.SS "\fBu16\fP* RGFW_gammaRamp::red"
array for the red channel 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
