.TH "RGFW_monitor" 3 "Tue Nov 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_monitor \- structure for monitor data  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBi32\fP \fBx\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBy\fP"
.br
.ti -1c
.RI "char \fBname\fP [128]"
.br
.ti -1c
.RI "float \fBscaleX\fP"
.br
.ti -1c
.RI "float \fBscaleY\fP"
.br
.ti -1c
.RI "float \fBpixelRatio\fP"
.br
.ti -1c
.RI "float \fBphysW\fP"
.br
.ti -1c
.RI "float \fBphysH\fP"
.br
.ti -1c
.RI "\fBRGFW_monitorMode\fP \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure for monitor data 
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_monitorMode\fP RGFW_monitor::mode"

.SS "char RGFW_monitor::name[128]"
monitor name 
.SS "float RGFW_monitor::physH"
monitor physical size in inches 
.SS "float RGFW_monitor::physW"

.SS "float RGFW_monitor::pixelRatio"
pixel ratio for monitor (1\&.0 for regular, 2\&.0 for hiDPI) 
.br
 
.SS "float RGFW_monitor::scaleX"

.SS "float RGFW_monitor::scaleY"
monitor content scale 
.SS "\fBi32\fP RGFW_monitor::x"

.SS "\fBi32\fP RGFW_monitor::y"
x - y of the monitor workarea 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
