.TH "RGFW_scaleUpdatedEvent" 3 "Tue Nov 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_scaleUpdatedEvent \- event data for when the window scale (DPI) is updated  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RGFW_eventType \fBtype\fP"
.br
.ti -1c
.RI "\fBRGFW_window\fP * \fBwin\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
event data for when the window scale (DPI) is updated 
.SH "Member Data Documentation"
.PP 
.SS "RGFW_eventType RGFW_scaleUpdatedEvent::type"
which event has been sent? 
.SS "\fBRGFW_window\fP* RGFW_scaleUpdatedEvent::win"
the window this event applies too (for event queue events) 
.SS "float RGFW_scaleUpdatedEvent::x"

.SS "float RGFW_scaleUpdatedEvent::y"
DPI scaling 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
