.TH "RGFW_monitorMode" 3 "Tue Nov 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_monitorMode \- monitor mode data | can be changed by the user (with functions)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBi32\fP \fBw\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBh\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBrefreshRate\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBred\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBblue\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBgreen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
monitor mode data | can be changed by the user (with functions) 
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP RGFW_monitorMode::blue"

.SS "\fBu8\fP RGFW_monitorMode::green"

.SS "\fBi32\fP RGFW_monitorMode::h"
monitor workarea size 
.SS "\fBu8\fP RGFW_monitorMode::red"

.SS "\fBu32\fP RGFW_monitorMode::refreshRate"
monitor refresh rate 
.SS "\fBi32\fP RGFW_monitorMode::w"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
