.TH "RGFW_window_src" 3 "Fri Dec 27 2024" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_window_src
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SH "Detailed Description"
.PP 
source data for the window (used by the APIs) 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
