.TH "RGFW_window" 3 "Wed Jul 16 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_window
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RGFW_window_src \fBsrc\fP"
.br
.ti -1c
.RI "void * \fBuserPtr\fP"
.br
.ti -1c
.RI "\fBRGFW_event\fP \fBevent\fP"
.br
.ti -1c
.RI "\fBRGFW_rect\fP \fBr\fP"
.br
.ti -1c
.RI "\fBRGFW_key\fP \fBexitKey\fP"
.br
.ti -1c
.RI "\fBRGFW_point\fP \fB_lastMousePoint\fP"
.br
.ti -1c
.RI "\fBu32\fP \fB_flags\fP"
.br
.ti -1c
.RI "\fBRGFW_rect\fP \fB_oldRect\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP RGFW_window::_flags"
windows flags (for RGFW to check) 
.SS "\fBRGFW_point\fP RGFW_window::_lastMousePoint"
last cusor point (for raw mouse data) 
.SS "\fBRGFW_rect\fP RGFW_window::_oldRect"
rect before fullscreen 
.SS "\fBRGFW_event\fP RGFW_window::event"
current event 
.SS "\fBRGFW_key\fP RGFW_window::exitKey"
which key RGFW_window_shouldClose checks\&. Settting this to RGFW_keyNULL disables the feature\&. 
.SS "\fBRGFW_rect\fP RGFW_window::r"
the x, y, w and h of the struct 
.SS "RGFW_window_src RGFW_window::src"
src window data 
.SS "void* RGFW_window::userPtr"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
