.TH "RGFW_info" 3 "Fri Jul 25 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_info
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRGFW_window\fP * \fBroot\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBwindowCount\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBeventLen\fP"
.br
.ti -1c
.RI "\fBRGFW_mouse\fP * \fBhiddenMouse\fP"
.br
.ti -1c
.RI "\fBRGFW_event\fP \fBevents\fP [\fBRGFW_MAX_EVENTS\fP]"
.br
.ti -1c
.RI "\fBu32\fP \fBapiKeycodes\fP [RGFW_keyLast]"
.br
.ti -1c
.RI "\fBu8\fP \fBkeycodes\fP [RGFW_OS_BASED_VALUE(256, 512, 128, 256)]"
.br
.ti -1c
.RI "const char * \fBclassName\fP"
.br
.ti -1c
.RI "\fBRGFW_bool\fP \fBuseWaylandBool\fP"
.br
.ti -1c
.RI "\fBRGFW_bool\fP \fBstopCheckEvents_bool\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBtimerOffset\fP"
.br
.ti -1c
.RI "char * \fBclipboard_data\fP"
.br
.ti -1c
.RI "char \fBdroppedFilesSrc\fP [\fBRGFW_MAX_PATH\fP *\fBRGFW_MAX_DROPS\fP]"
.br
.ti -1c
.RI "char ** \fBdroppedFiles\fP"
.br
.ti -1c
.RI "\fBRGFW_window\fP * \fBcurrent\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP RGFW_info::apiKeycodes[RGFW_keyLast]"

.SS "const char* RGFW_info::className"

.SS "char* RGFW_info::clipboard_data"

.SS "\fBRGFW_window\fP* RGFW_info::current"

.SS "char** RGFW_info::droppedFiles"

.SS "char RGFW_info::droppedFilesSrc[\fBRGFW_MAX_PATH\fP *\fBRGFW_MAX_DROPS\fP]"

.SS "\fBi32\fP RGFW_info::eventLen"

.SS "\fBRGFW_event\fP RGFW_info::events[\fBRGFW_MAX_EVENTS\fP]"

.SS "\fBRGFW_mouse\fP* RGFW_info::hiddenMouse"

.SS "\fBu8\fP RGFW_info::keycodes[RGFW_OS_BASED_VALUE(256, 512, 128, 256)]"

.SS "\fBRGFW_window\fP* RGFW_info::root"

.SS "\fBRGFW_bool\fP RGFW_info::stopCheckEvents_bool"

.SS "\fBu64\fP RGFW_info::timerOffset"

.SS "\fBRGFW_bool\fP RGFW_info::useWaylandBool"

.SS "\fBi32\fP RGFW_info::windowCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
