.TH "RGFW_image" 3 "Wed Jul 30 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_image
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP * \fBdata\fP"
.br
.ti -1c
.RI "\fBRGFW_area\fP \fBsize\fP"
.br
.ti -1c
.RI "RGFW_format \fBformat\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP* RGFW_image::data"
raw image data 
.SS "RGFW_format RGFW_image::format"
image format 
.SS "\fBRGFW_area\fP RGFW_image::size"
image size 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
