.TH "RGFW_area" 3 "Sat Jul 19 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_area
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBw\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
basic area type, if there's not already a area type of choice 
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP RGFW_area::h"

.SS "\fBu32\fP RGFW_area::w"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
