.TH "RGFW_debugInfo" 3 "Thu Apr 2 2026" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_debugInfo \- data for debug messages  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RGFW_debugType \fBtype\fP"
.br
.ti -1c
.RI "RGFW_errorCode \fBcode\fP"
.br
.ti -1c
.RI "const char * \fBmsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
data for debug messages 
.SH "Member Data Documentation"
.PP 
.SS "RGFW_errorCode RGFW_debugInfo::code"
the code for the specific type of debug message 
.SS "const char* RGFW_debugInfo::msg"
string message 
.SS "RGFW_debugType RGFW_debugInfo::type"
the type of message 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
