.TH "RGFW_keyState" 3 "Tue Jun 17 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_keyState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRGFW_bool\fP \fBcurrent\fP: 1"
.br
.ti -1c
.RI "\fBRGFW_bool\fP \fBprev\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
optional init/deinit function 
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_bool\fP RGFW_keyState::current"

.SS "\fBRGFW_bool\fP RGFW_keyState::prev"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
