.TH "RGFW_colorLayout" 3 "Fri Jan 30 2026" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_colorLayout \- layout struct for mapping out format types  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBi32\fP \fBr\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBg\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBb\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBa\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBchannels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
layout struct for mapping out format types 
.SH "Member Data Documentation"
.PP 
.SS "\fBi32\fP RGFW_colorLayout::a"

.SS "\fBi32\fP RGFW_colorLayout::b"

.SS "\fBu32\fP RGFW_colorLayout::channels"

.SS "\fBi32\fP RGFW_colorLayout::g"

.SS "\fBi32\fP RGFW_colorLayout::r"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
