.TH "RGFW_window" 3 "Tue Jul 23 2024" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_window
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRGFW_window_src\fP \fBsrc\fP"
.br
.ti -1c
.RI "\fBRGFW_Event\fP \fBevent\fP"
.br
.ti -1c
.RI "\fBRGFW_rect\fP \fBr\fP"
.br
.ti -1c
.RI "\fBRGFW_point\fP \fB_lastMousePoint\fP"
.br
.ti -1c
.RI "u32 \fBfpsCap\fP"
.br
.ti -1c
.RI "u32 \fB_winArgs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBRGFW_Event\fP RGFW_window::event"
current event 
.SS "u32 RGFW_window::fpsCap"
the fps cap of the window should run at (change this var to change the fps cap, 0 = no limit) 

.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
