.TH "RGFW_point" 3 "Tue Jul 22 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGFW_point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGFW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBi32\fP \fBx\fP"
.br
.ti -1c
.RI "\fBi32\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
basic vector type, if there's not already a point/vector type of choice 
.SH "Member Data Documentation"
.PP 
.SS "\fBi32\fP RGFW_point::x"

.SS "\fBi32\fP RGFW_point::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
