.TH "Supporting" 3 "Wed Feb 12 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Supporting \- Supporting
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP \fBu64\fP \fBRGFW_getTime\fP (void)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBu64\fP \fBRGFW_getTimeNS\fP (void)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_sleep\fP (\fBu64\fP milisecond)"
.br
.ti -1c
.RI "typedef \fBRGFW_ENUM\fP (\fBu8\fP, \fBRGFW_key\fP)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP \fBu32\fP \fBRGFW_apiKeyToRGFW\fP (\fBu32\fP keycode)"
.br
.ti -1c
.RI "typedef \fBRGFW_ENUM\fP (\fBu8\fP, RGFW_mouseIcons)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP \fBu32\fP RGFW_apiKeyToRGFW (\fBu32\fP keycode)"

.SS "typedef RGFW_ENUM (\fBu8\fP, \fBRGFW_key\fP)"
key codes and mouse icon enums 
.SS "typedef RGFW_ENUM (\fBu8\fP, RGFW_mouseIcons)"

.SS "\fBRGFWDEF\fP \fBu64\fP RGFW_getTime (void)"
get time in seconds 
.SS "\fBRGFWDEF\fP \fBu64\fP RGFW_getTimeNS (void)"
get time in nanoseconds 
.SS "\fBRGFWDEF\fP void RGFW_sleep (\fBu64\fP milisecond)"
sleep for a set time 
.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
