.TH "Threads" 3 "Sun Mar 9 2025" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Threads \- Threads
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef DWORD(__stdcall * \fBRGFW_threadFunc_ptr\fP) (LPVOID lpThreadParameter)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRGFWDEF\fP \fBRGFW_thread\fP \fBRGFW_createThread\fP (\fBRGFW_threadFunc_ptr\fP ptr, void *args)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_cancelThread\fP (\fBRGFW_thread\fP thread)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_joinThread\fP (\fBRGFW_thread\fP thread)"
.br
.ti -1c
.RI "\fBRGFWDEF\fP void \fBRGFW_setThreadPriority\fP (\fBRGFW_thread\fP thread, \fBu8\fP priority)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2

.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef DWORD(__stdcall * RGFW_threadFunc_ptr) (LPVOID lpThreadParameter)"
threading functions
.PP
NOTE! (for X11/linux) : if you define a window in a thread, it must be run after the original thread's window is created or else there will be a memory error 
.SH "Function Documentation"
.PP 
.SS "\fBRGFWDEF\fP void RGFW_cancelThread (\fBRGFW_thread\fP thread)"
cancels a thread 
.SS "\fBRGFWDEF\fP \fBRGFW_thread\fP RGFW_createThread (\fBRGFW_threadFunc_ptr\fP ptr, void * args)"
create a thread 
.SS "\fBRGFWDEF\fP void RGFW_joinThread (\fBRGFW_thread\fP thread)"
join thread to current thread 
.SS "\fBRGFWDEF\fP void RGFW_setThreadPriority (\fBRGFW_thread\fP thread, \fBu8\fP priority)"
sets the priority priority 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for RGFW from the source code\&.
